### ISSUE TITLE
Hello Sir

### ISSUE THREAD

**Issue by Pocker88** [engageub/InternetIncome#1]
Can you pls make some ReCaptcha v2 solver?!?

**Comment by engageub** [comment]
Hello,
This is not the right place to discuss recaptcha solver. If there is any issue with this script, you may raise an issue. 
Please note that github has multiple recaptcha solvers available for free. You may have a look at them.
I am closing this, since this is not an issue with the script.
Thank you

**Comment by Pocker88** [comment]
Ok thx
