### ISSUE TITLE
[Feature Request]Add delay in startup containers to properties.conf

### ISSUE THREAD

**Issue by poga88887** [engageub/InternetIncome#30]
I was just fiddeling around with this project and it seems perfect so far, the only issue I'm having is that when I use a lower end server (1 or 2 cores) and try to launch multiple session with proxies is that the machine freezes because they launch so quickly after one another.

Would it be possible to add a delay to the properties.conf for inbetween each launch specified in seconds or milliseconds?

**Comment by engageub** [comment]
Hi,

The script already does serial execution and it runs only after the
previous command is executed.
There are chances that when the previous application starts running, it may
download assets and start execution inside, when the container starts.
Ideally cpu and memory should be checked instead of setting delay since it
cannot be assured that a particular delay will be sufficient.
However this has been tested on low end servers with 1 core 1gb ram and I
agree this happens when containers with multiple proxies are run but it
waits for few minutes before continuing. It does not permanently freeze
unless your memory and cpu are not sufficient and completely filled. Make
sure you have enough swap space on your PC.
When you start the script, open the other terminal and monitor the cpu and
memory usage.


Thank you

**Comment by engageub** [comment]
Could you please provide the working proxy provider for residential proxies if you have apart from the ones mentioned in the wiki. 

Thank you

**Comment by poga88887** [comment]
> Could you please provide the working proxy provider for residential proxies if you have apart from the ones mentioned in the wiki.
> 
> Thank you

I will if I find one! Thanks for the quick response.

**Comment by engageub** [comment]
So, this is happening with direct connection?

Thank you

**Comment by poga88887** [comment]
No I was testing the proxy capabilities with free public ones that passed a simple checker online

**Comment by engageub** [comment]
Delay between container start has been added to test branch.

https://github.com/engageub/InternetIncome/tree/test

Thank you
