### ISSUE TITLE
Can you make Firefox german?

### ISSUE THREAD

**Issue by copystring** [engageub/InternetIncome#31]
Not sure if it makes a difference, but it feels better, if it's in German. Maybe it'll make a few more points.

Also getting this message:
![image](https://github.com/engageub/InternetIncome/assets/1298861/b2c63269-53ff-4664-894b-fe7c56d46705)

**Comment by engageub** [comment]
Hi,

You need to manually change for now, if you wish to change the language.  You need to change the language in default firefox.zip file and store it in your folder. This way even if it cleans up the container after one hour, your default data will not be changed. 

To do this, you need to change the language settings in your browser from the UI. Then copy the data into default firefox data folder and zip it to firefox.zip

What you will be doing is overriding the default firefox data that has been downloaded from github.

Automating based on IP address may not yield correct results since the database ebesucher checks will be different. 
For US proxies, it was showing UK flag when it was used earlier. So there will be discrepancy if automation is done based on IP address.

There are already open issues raised for docker firefox to change language. Please see below.
https://support.mozilla.org/en-US/kb/use-firefox-another-language
https://github.com/jlesage/docker-firefox/issues?q=language+is%3Aopen


Thank you


Thank you

**Comment by engageub** [comment]
Hello,
If you are using firefox, there is an option to change the language.
You can try to add the following option in internetIncome.sh file `-e LANG="de_DE.UTF8"`
I have not tried this yet.
For more details on various options in firefox, please refer the following link. 

https://github.com/jlesage/docker-firefox?tab=readme-ov-file#environment-variables

Thank you
