### ISSUE TITLE
Peer2profit docker issue

### ISSUE THREAD

**Issue by hoainv1807** [engageub/InternetIncome#32]
can not pull docker file of Peer2profit
![IMG_20230702_145400_756](https://github.com/engageub/InternetIncome/assets/47892115/084374c1-6c44-4c02-9d20-a1f8e5138ea3)

**Comment by engageub** [comment]
Hi,
The official docker image from peer2profit has been removed.
https://hub.docker.com/r/peer2profit/peer2profit_linux

The linux version has been downgraded from their website. 
Please do not use it until they update it.  You will need to remove your email address from properties.conf to continue using other docker containers.


Thank you

**Comment by engageub** [comment]
If you have proxies with username and password you can add them in peer2profit dashboard directly.

Thank you

**Comment by engageub** [comment]
Peer2profit does not officially support docker now due to potential abuse by some users who tried to install on other user's devices as a malware without consent, to generate earnings from it. 
You may also refer to the following news article. 

https://www.akamai.com/blog/security-research/proxyjacking-new-campaign-cybercriminal-side-hustle?fbclid=IwAR0ziFMl4fzxUqVm4stqI7DcEch8bPse5-LfR8wZW4KXf0anukZYBvB3xWk

Thank you

**Comment by hoainv1807** [comment]
Thank you

**Comment by engageub** [comment]
Hi,
Peer2profit has been added back. Please have a look at the latest peer2profit telegram link mentioned.
Thank you
