### ISSUE TITLE
what is the Average Earnings per IP on each platform?

### ISSUE THREAD

**Issue by SkullFace141** [engageub/InternetIncome#4]
what is the Average Earnings per IP on each platform?

**Comment by engageub** [comment]
Hi @SkullFace141 ,

It is mentioned in the description already. It depends on the location of the proxy you are using and the type of app.
I cannot give you exact details about this unless the app is consistently sending traffic and the amount per gb is same across all locations. 
For each platform do you mean each app?  If so you will need to check the website of the app since most of the apps are location dependent. 
But consider it to be 1-2$ per app per month on an average and use it. 


Thank you
