### ISSUE TITLE
Error while linking device The device is linked to someone else

### ISSUE THREAD

**Issue by hieunguyen8794** [engageub/InternetIncome#40]
Get error when link device. "Error while linking device The device is linked to someone else"

I rented a shared proxy that is being used by 2-3 people, and I keep getting this error when linking earn-app accounts. 

I'm not sure if it's because of duplicate proxies or if there's an issue with my device ID.

I noticed that the UUID is generated based on the current time, so if someone generates one at the same time as me, will this cause the error?

**Comment by engageub** [comment]
Hi,
It looks like the UUID generated is already used by someone else so that person may be earning from your UUID. Its not based only on date and time. 
Please delete it and create again. You also need to delete backup to delete the Ids generated. 
If you do not wish to delete backups, you can generate a random UUID if you know how to do it and then add in earnapp.txt file by replacing the existing one. 

Thank you

**Comment by engageub** [comment]
Closing this. Please reopen if you see issues further.
Thank you
