### ISSUE TITLE
problem support mystnodes

### ISSUE THREAD

**Issue by contidz** [engageub/InternetIncome#47]
![image](https://github.com/engageub/InternetIncome/assets/137675836/f5240658-3d5f-4263-a33f-2766da84c9b5)
when i enable mystnode node in control panel i get the url set as shown but i paste the link in the browser i cant access the link, did i misunderstand how to run mystnode script

**Comment by engageub** [comment]
Please note that there is an ongoing issue with proxies in mystnodes. Please read the [FAQ](https://github.com/engageub/InternetIncome#thinking-why-is-mysterium-node-not-workingquestion) section.
However it should not affect the url to be opened in the browser. You may not see earnings even if the node is online while using proxy. 
Does your linux have GUI access? If not, please use the following command to access each server globally.
If your port number is 2000, please use the following command to get the global url with which you can access it anywhere temporarily.
Replace the port numbers to with other ports to access other nodes.
```
ssh -R 80:localhost:2000 serveo.net
```
If you are using with direct connection, please enable logs in properties.conf and check the container logs for any potential issues.

Closing this since this is already mentioned as part of FAQ. 

Thank you
