### ISSUE TITLE
Hello Sir.

### ISSUE THREAD

**Issue by Pocker88** [engageub/InternetIncome#48]
I wanted to buy your captcha solver. And I sent the wrong number of coins to the right address. And I can't get neither your solver nor my coins back. Please help me. Here is the transaction hash 9b2478abaf19cf8d094f1318ed1f25eca21eaa307320163da2932ae5a541fb5b. 
![Screenshot_2023-08-20-23-52-39-28_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/engageub/InternetIncome/assets/79075067/988f5150-b440-4655-b9b4-5b9ad93828f8)
![Screenshot_2023-08-20-23-54-48-19_4d38fce200f96aeac5e860e739312e76](https://github.com/engageub/InternetIncome/assets/79075067/5554f58c-33b4-495b-8cf6-a9ea321fb374)

**Comment by engageub** [comment]
Hi,
This is not related to Income Income script. Please check with gourl support team on how to get your payment back.
https://gourl.io/view/contact/Contact_Us.html
I do not own the payment gateway. So please check with them to get your money back mentioning the details. 
You may receive the response  from them in 5 business days. 
Closing this since it is unrelated to InternetIncome script. 

Thank you
