### ISSUE TITLE
Earn app device not found 

### ISSUE THREAD

**Issue by ppzzAn** [engageub/InternetIncome#68]
Hi

Bug with device linked to someone else is gone, thanks for that. Now I notice another one which is "Device not found"
1 node from - 20.

**Comment by engageub** [comment]
Hi,
It can occur anytime even with this but the randomness might have changed. Its due to the limited number of 32 character string.  The other version of earnapp docker requires systemd and privileges which has some security concerns so it was not added to the script. 
Device not found occurs when the proxy is not working as expected.
Could you please look into earnapp logs for the respective node which is not working.
Please enable logs in properties.conf file and look into earnapp logs.

Thank you

**Comment by engageub** [comment]
Hi,
Could you please update if there is any issue identified in the logs. Is your proxy working fine. 

Thank you

**Comment by ppzzAn** [comment]
Hi

I've enabled logging in settings, where I can find them on ubuntu ?

**Comment by ppzzAn** [comment]
update
Now it's linked fine, I think proxy could not connect and that's why this error appear.

Thanks for response

closed.
