### ISSUE TITLE
Proxy + direct connection

### ISSUE THREAD

**Issue by copystring** [engageub/InternetIncome#81]
Hi,

is it possible to create another container for direct connection when using proxies?
For example 10 proxy containers + 1 container for direct connection?

**Comment by engageub** [comment]
Yes, you can do that on test branch.

Thank you

**Comment by copystring** [comment]
Is it this `USE_DIRECT_CONNECTION`?

**Comment by engageub** [comment]
Yes, thats correct. Use direct and proxy at same time and let me know.

**Comment by copystring** [comment]
I will test this tomorrow.

**Comment by engageub** [comment]
Thank you. Please close the issue. I am replying through email.

**Comment by engageub** [comment]
Hi,
Were you able to get this working. This feature was not intentional as it would be better to have separate folders for connection types. The test branch is for advanced users.
Recently some updates have been made with respect to earnapp and proxyrack when both are used.
Users who are using test branch may not be aware that both work at same time if direct connection is enabled.
In fact different types of connections work at the same time when they are enabled including vpns and multi ip.

Thank you

**Comment by copystring** [comment]
Hi,

not yet. My server broke. I need to repair this first.
